server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root /usr/share/nginx/html/;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        # add_header X-Frame-Options ALLOWALL;  
        # add_header X-Frame-Options DENY; 
        # add_header X-Frame-Options SANEORIGIN; 
        # add_header X-Frame-Options ALLOW-FROM uri; 
 
    }
    # location /api-mintime {
	# proxy_pass http://127.0.0.1:5000/server;
	# proxy_cookie_path /server /api-mintime;
# }
}


 